// JavaScript 
//获取验证码图片
function verify_Create(parent){
	var newa=document.createElement('img');
	var request=new XMLHttpRequest();
	request.open('GET',"http://49.140.166.99:8080/eLife/api/server.php?action=getVerify",true);
	request.send();
	request.onreadystatechange=function(){
		if(request.readyState===4){
			if(request.status===200){
				newa.src="http://49.140.166.99:8080/eLife/api/server.php?action=getVerify";
			}
		}
	}
	newa.setAttribute('id','verify_img');
	newa.setAttribute('width','80px');
	newa.setAttribute('height','28px');
	parent.appendChild(newa);
}
//刷新验证码图片
function verify_F5(){
    var verify=document.getElementById('verify');
    var parent=verify.parentNode;
	parent.removeChild(verify_img);
	verify_Create(parent);
}
$(document).ready(function(){
	//选择注册途径css
	$("#email_selected").click(function(){
		$("#phone_signup").css('display','none');
		$("#email_signup").css('display','block');
		$("#phone_selected").css('background','rgba(0,175,66,0.3)');
		$("#phone_selected").stop().animate({left:'22px'},300);
	});
	$("#phone_selected").click(function(){
		$("#phone_signup").css('display','block');
		$("#email_signup").css('display','none');
		$("#email_selected").css('background','rgba(0,175,66,0.3)');
		$("#email_selected").stop().animate({left:'22px'},300);
	});
	$("#phone_selected").mouseover(function(){
		$(this).css('background','rgba(0,175,66,1)');
		$(this).stop().animate({left:'52px'},300);
	});
	$("#phone_selected").mouseout(function(){
		if($("#email_signup").is(":hidden")){}else{
		$(this).css('background','rgba(0,175,66,0.3)');
		$(this).stop().animate({left:'22px'},300);}
	});
	$("#email_selected").mouseover(function(){
		$(this).css('background','rgba(0,175,66,1)');
		$(this).stop().animate({left:'52px'},300);
	});
	$("#email_selected").mouseout(function(){
		if($("#email_signup").is(":hidden")){
		$(this).css('background','rgba(0,175,66,0.3)');
		$(this).stop().animate({left:'22px'},300);}
	});
	//同意相关条款css
	$("#phone_i_agree").click(function(){
		if(!$("#phone_i_agree").is(':checked')){
			$("#phone_register_now").css('background-color','#858585');
			$("#phone_register_now").css('color','#00AF42');
			$("#phone_register_now").css('cursor','default');
		}
		else{
			$("#phone_register_now").css('background-color','#00AF42');
			$("#phone_register_now").css('color','#FFF');
			$("#phone_register_now").css('cursor','pointer');
		}
	});
	$("#i_agree").click(function(){
		if(!$("#i_agree").is(':checked')){
			$("#register_now").css('background-color','#858585');
			$("#register_now").css('color','#00AF42');
			$("#register_now").css('cursor','default');
		}
		else{
			$("#register_now").css('background-color','#00AF42');
			$("#register_now").css('color','#FFF');
			$("#register_now").css('cursor','pointer');
		}
	});
	//手机注册表单验证
	$("#phone_register_form").validate({
		errorPlacement: function(error,element){
			element.parent().next().html(error);
		},
		rules:{
			phone:{
				required:true,
				minlength:11,
				maxlength:11,
				remote:{
                	url: "http://49.140.166.99:8080/huiwanspace/api/webServer.php",
                	type: "Post",
					dataType:"json",
                	data: {
						action:"phoneNoExist",
						phone:function(){return $("#phone").val()}
					}
            	}
            },
			phone_password:{
				required:true,
				minlength:6,
				maxlength:16
			},
			phone_password_again:{
				required:true,
				minlength:6,
				maxlength:16,
				equalTo:"#phone_password"
			}
		},
		messages:{
			phone:{
				required:"*必须填写手机号码",
				minlength:"*请输入正确的手机号码",
				maxlength:"*请输入正确的手机号码",
				remote:"*该手机号码已被注册"
			},
			phone_password:{
				required:"*必须填写密码",
				minlength:"*密码不能少于6字节",
				maxlength:"*密码不能多于16字节"
			},
			phone_password_again:{
				required:"*必须再次填写密码",
				minlength:"*密码不能少于6字节",
				maxlength:"*密码不能多于16字节",
				equalTo:"*密码不一致"
			}
		}
	});
	$("#phone").focus(function(){
		$("#error_phone").css("color","#F00");
	});
	$("#phone").blur(function(){
		setTimeout(function(){
			if(($("#error_phone").text()==""||$("#error_phone").text()=="*该手机号码可以注册")&&$("#phone").val()!=""){
				$("#error_phone").text("*该手机号码可以注册");
				$("#error_phone").css("color","green");}
		},600)
	});
	//邮箱注册表单验证
	$("#register_form").validate({
		errorPlacement: function(error,element){
			element.parent().next().html(error);
		},
		rules:{
			email:{
				required:true,
				email:true,
				remote:{
                	url: "http://49.140.166.99:8080/huiwanspace/api/webServer.php",
                	type: "Post",
					dataType:"json",
                	data: {
						action:"emailNoExist",
						email:function(){return $("#email").val()}
					}
            	}
			},
			email_password:{
				required:true,
				minlength:6,
				maxlength:16
			},
			email_password_again:{
				required:true,
				minlength:6,
				maxlength:16,
				equalTo:"#email_password"
			}
		},
		messages:{
			email:{
				required:"*必须填写邮箱地址",
				email:"*必须填写正确的邮箱地址",
				remote:"*该邮箱地址已被注册"
			},
			email_password:{
				required:"*必须填写密码",
				minlength:"*密码不能少于6字节",
				maxlength:"*密码不能多于16字节"
			},
			email_password_again:{
				required:"*必须再次填写密码",
				minlength:"*密码不能少于6字节",
				maxlength:"*密码不能多于16字节",
				equalTo:"*密码不一致"
			}
		}
	});
	$("#email").focus(function(){
		$("#error_email").css("color","#F00");
	});
	$("#email").blur(function(){
		setTimeout(function(){
			if(($("#error_email").text()==""||$("#error_email").html()=="*该邮箱地址可以注册")&&$("#email").val()!=""){
				$("#error_email").html("*该邮箱地址可以注册");
				$("#error_email").css("color","green");}
		},600)
	});
	//获取短信验证码按钮css
	$("#get_phone_verify").mouseover(function(){
		$("#get_phone_verify").css('background','rgba(0,175,66,1)');
		$("#get_phone_verify").css('box-shadow','1.2px 1.2px 4px #CCC');
	});
	$("#get_phone_verify").mouseout(function(){
		$("#get_phone_verify").css('background','rgba(0,175,66,0.5)');
		$("#get_phone_verify").css('box-shadow','none');
	});
	//获取短信验证码
	$("#get_phone_verify").click(function get(){
		var $verify_time=60;
		var $phoneverifyflag=0;
		$.ajax({
			type:"POST",
			url:"http://49.140.166.99:8080/huiwanspace/api/webServer.php",
			dataType:"json",
			data:{
				action:"getMessageForReg",
				phone:$("#phone").val()
			},
			success:function(data){
				if(data.status==1){
					alert("验证码发送成功，请留意手机短信!")
					$phoneverifyflag=data.status;
				}
				else{
					$phoneverifyflag=data.status;
					$("#error_information_text").html("*"+data.message);
					$("#error_information_display").css('display','block');
					scroll(0,0);	
				}
			},
			error:function(jqXHR){
				alert("发生错误："+jqXHR.status);
			}
		});
		$(function time(){
			if($verify_time==0){
				$phoneverifyflag=0;
				$("#get_phone_verify").html('获取短信验证码');
				$("#get_phone_verify").css('background','rgba(0,175,66,0.5)');
				$("#get_phone_verify").css('box-shadow','none');
				$("#get_phone_verify").css('cursor','pointer');
				$("#get_phone_verify").on('mouseover',function(){
					$("#get_phone_verify").css('background','rgba(0,175,66,1)');
					$("#get_phone_verify").css('box-shadow','1.2px 1.2px 4px #CCC');
				});
				$("#get_phone_verify").on('mouseout',function(){
					$("#get_phone_verify").css('background','rgba(0,175,66,0.5)');
					$("#get_phone_verify").css('box-shadow','none');
				});
				$("#get_phone_verify").on('click',get);
				$verify_time=60;
			}
			else if($phoneverifyflag==1&&$verify_time!=0){
				$("#get_phone_verify").html($verify_time+'s后重新发送');
				$("#get_phone_verify").css('background','rgba(153,153,153,0.5)');
				$("#get_phone_verify").css('box-shadow','none');
				$("#get_phone_verify").css('cursor','default');
				$("#get_phone_verify").off('mouseover');
				$("#get_phone_verify").off('mouseout');
				$("#get_phone_verify").off('click');
				$verify_time--;
				setTimeout(function(){time();},1000);
			}
		});
	});
	//手机注册
	$("#phone_register_now").click(function(){
		if($("#phone_i_agree").is(':checked')){
			$.ajax({
			type:"POST",
			url:"http://49.140.166.99:8080/huiwanspace/api/webServer.php",
			dataType:"json",
			data:{
				action:"userReg",
				phone:$("#phone").val(),
				password:$("#phone_password").val(),
				messageCode:$("#phone_verify").val()
			},
			success:function(data){
				if(data.status==1){
					alert("欢迎来到汇玩网！Have a good day");
					setTimeout(function(){
						window.location.href="../主页/hostpage.html";
					},500);	
				}
				else if(data.status!=1){
					$("#error_information_text").html("*"+data.message);
					$("#error_information_display").css('display','block');
					scroll(0,0);
				}
			},
			error:function(jqXHR){
				alert("发生错误："+jqXHR.status);
			}
		});
		}
		else{//没同意相关条款
			$("#error_information_text").html("*您还没有同意相关条款,暂不能注册");
			$("#error_information_display").css('display','block');
			scroll(0,0);
		}
	});
	//换一张图片验证码
	$("#change_verify").click(function(){
		verify_F5();
	});
	//邮箱注册
	$("#register_now").click(function(){
		if($("#i_agree").is(':checked')){
			$.ajax({
			type:"POST",
			url:"http://49.140.166.99:8080/huiwanspace/api/webServer.php",
			dataType:"json",
			data:{
				action:"userReg",
				password:$("#email_password").val(),
				email:$("#email").val(),
				verify:$("#verify").val()
			},
			success:function(data){
				if(data.status==1){
					alert("欢迎来到汇玩网！Have a good day");
					setTimeout(function(){
						window.location.href="../主页/hostpage.html";
					},500);	
				}
				else{
					$("#error_information_text").html("*"+data.message);
					$("#error_information_display").css('display','block');
					scroll(0,0);	
				}
			},
			error:function(jqXHR){
				alert("发生错误："+jqXHR.status);
			}
		});
		}
		else{//没同意相关条款
			$("#error_information_text").html("*您还没有同意相关条款,暂不能注册");
			$("#error_information_display").css('display','block');
			scroll(0,0);
		}
	});
})
